### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
I have Updated README.md File.Please merge my PR #2 .

### CODE REVIEW

**Comment by gracyashhh** [comment]
Thanks for your contribution @shahbazalam07

**Comment by ghost** [comment]
I will be very thankful if you add me to the contributor list.

**Comment by gracyashhh** [comment]
Yes, but I don't I added anyone as such.. doesn't it get updated by itself as the PR gets merged?

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
only my udpaded README.md is merged not my website as only one merged file is showing to me.
So,kindly consider it.

**Comment by gracyashhh** [comment]
I think you will have to check my repository folders yourself, also this link `https://hacktoberfestchecker.jenko.me/user/shahbazalam07` if you'd like, I'm adding screenshots for your clarity 🙃


check
resolved

**Comment by ghost** [comment]
Oo I got it . Thanks🙂

**Pull request merged**
